### ISSUE TITLE
Retain leiningen build

### ISSUE THREAD

**Issue by pmonks** [irresponsible/tentacles#3]
Amongst other benefits, Leiningen is supported by [jitpack.io](https://jitpack.io); an invaluable tool in the period leading up to your first Clojars release.

**Comment by kentfredric** [comment]
A quick skim of [this suggests](https://jitpack.io/docs/BUILDING/#build-customization) whatever magic I end up having to add for it to build on travis could theoretically be abused to build on jitpack. 

The time and permissions constraints seem similar enough to travis. 

Just not sure how viable that is.

**Comment by pmonks** [comment]
Cool I didn't know about that. Alternatively, you could just start pushing 0.6.0-SNAPSHOT versions to Clojars?

**Comment by kentfredric** [comment]
Please double check what I've done works. 

The logic is a little hairy, but upstream are anticipating this usecase and state this is what to do, and it works :) 

https://github.com/jitpack/jitpack.io/issues/488

**Comment by pmonks** [comment]
I didn't have to verify it as it's now in Clojars.  Thanks for your quick turnaround on this though - this is an awesome library and I'm glad someone has chosen to continue Raynes' great work.
