### ISSUE TITLE
boot-test is not a runtime dependency

### ISSUE THREAD

**Issue by codahale** [irresponsible/tentacles#4]
Hello! First, thanks for taking over tentacles — I really appreciate you all stepping up.

Second, it looks like `adzerk/boot-test` snuck in as an accidental dependency: https://github.com/irresponsible/tentacles/blob/master/build.boot#L10. It's easy enough for me to exclude that, but it should probably be moved to a development dependency.

**Comment by jjl** [comment]
Thanks for the bug report. I've pushed a fix and @kentfredric will ship it as soon as he gets a chance.

**Comment by kentfredric** [comment]
Fixed in fcea76a0d5bd684389475b1f8b58b63b0b0a03e4 

Thanks.
